title: Pixel Grimoire
tagline: My learning blog
url: "https://amanthul.github.io"
baseurl: ""
author:
  name: Rudy Zhang
  url: https://haochen-rudy-zhang.me

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Build Settings

paginate: 5

tags_path: /tags/
categories_path: /categories/
